environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew build --info --no-daemon

artifacts:
  - path: 'common\build\libs\*.jar'
    name: common
  - path: 'impl-builder\build\libs\*.jar'
    name: impl-builder
  - path: 'impl-gap\build\libs\*.jar'
    name: impl-gap
  - path: 'impl-line\build\libs\*.jar'
    name: impl-line
  - path: 'gap-list\build\libs\*.jar'
    name: gap-list
#
